#![allow(missing_docs, clippy::expect_used, clippy::panic, clippy::unwrap_used)]

//! The shipped verifier must accept metadata produced by the release scripts.
//!
//! The fixtures in `tests/fixtures` were generated by
//! `scripts/generate-release-manifest.mjs` and `scripts/generate-release-index.mjs`
//! and signed with the production release key. They pin the wire contract
//! between the Node signing scripts and this Rust verifier: signature encoding,
//! canonical byte layout and the strict manifest schema. A change on either side
//! that would make a shipped client reject a real published release fails here
//! instead of in the field.

use rc_updater::{
    Architecture, InstallationType, ManifestPolicy, ManifestSignaturePolicy,
    ManifestSignatureVerifier, OperatingSystem, PackageFormat, PlatformInfo, PlatformKey,
    ReleaseIndex, ReleaseManifest,
};

/// Public half of the release signing key, as embedded in shipped builds.
const RELEASE_PUBLIC_KEY: &str = "YW01mVPd9F6R/WxJJM2+FB2rCDaxLUUxQYZ0/HaHpf0=";

const MANIFEST: &[u8] = include_bytes!("fixtures/release-manifest.json");
const MANIFEST_SIG: &str = include_str!("fixtures/release-manifest.json.sig");
const INDEX: &[u8] = include_bytes!("fixtures/release-index.json");
const INDEX_SIG: &str = include_str!("fixtures/release-index.json.sig");

fn policy() -> ManifestSignaturePolicy {
    ManifestSignaturePolicy::Required {
        public_keys_base64: vec![RELEASE_PUBLIC_KEY.to_string()],
    }
}

#[test]
fn a_script_signed_manifest_verifies_against_the_release_key() {
    ManifestSignatureVerifier
        .verify(MANIFEST, Some(MANIFEST_SIG), &policy())
        .expect("a manifest signed by the release key must verify");
}

#[test]
fn a_script_signed_index_verifies_against_the_release_key() {
    ManifestSignatureVerifier
        .verify(INDEX, Some(INDEX_SIG), &policy())
        .expect("an index signed by the release key must verify");
}

#[test]
fn tampered_metadata_is_rejected() {
    for (name, bytes, signature) in [
        ("manifest", MANIFEST, MANIFEST_SIG),
        ("index", INDEX, INDEX_SIG),
    ] {
        let mut tampered = bytes.to_vec();
        let last = tampered.len() - 3;
        tampered[last] ^= 0x01;
        assert!(
            ManifestSignatureVerifier
                .verify(&tampered, Some(signature), &policy())
                .is_err(),
            "a modified {name} must not verify",
        );
    }
}

#[test]
fn metadata_signed_by_an_untrusted_key_is_rejected() {
    let untrusted = ManifestSignaturePolicy::Required {
        public_keys_base64: vec!["A".repeat(43) + "="],
    };
    assert!(
        ManifestSignatureVerifier
            .verify(MANIFEST, Some(MANIFEST_SIG), &untrusted)
            .is_err(),
        "only the configured release keys may authorise an update",
    );
}

#[test]
fn an_empty_keyring_refuses_to_accept_anything() {
    let empty = ManifestSignaturePolicy::Required {
        public_keys_base64: Vec::new(),
    };
    assert!(
        ManifestSignatureVerifier
            .verify(MANIFEST, Some(MANIFEST_SIG), &empty)
            .is_err(),
        "a build with no trusted key must not accept metadata",
    );
}

#[test]
fn a_missing_signature_is_refused_when_signatures_are_required() {
    assert!(
        ManifestSignatureVerifier
            .verify(MANIFEST, None, &policy())
            .is_err(),
        "unsigned metadata must not be accepted under a Required policy",
    );
}

#[test]
fn script_output_satisfies_the_strict_manifest_schema() {
    let manifest = ReleaseManifest::parse(MANIFEST, &ManifestPolicy::default())
        .expect("generated manifests must satisfy the schema the client enforces");
    assert_eq!(manifest.version, "0.1.1");
    assert!(
        !manifest.release_notes.is_empty(),
        "generated notes must reach the manifest so users see what changed",
    );
}

#[test]
fn script_output_satisfies_the_strict_index_schema() {
    let index = ReleaseIndex::parse(INDEX, &ManifestPolicy::default())
        .expect("generated indexes must satisfy the schema the client enforces");
    assert_eq!(index.releases.len(), 1);
    assert!(
        index.releases[0].manifest_url.starts_with("https://"),
        "release metadata must only be fetched over https",
    );
}

/// A Windows machine on the previous version, as a shipped client sees itself.
fn windows_client() -> PlatformInfo {
    PlatformInfo {
        os: OperatingSystem::Windows,
        os_version: "10.0.26200".to_string(),
        os_build: Some(26_200),
        cpu_architecture: Architecture::X64,
        installation_architecture: Architecture::X64,
        key: PlatformKey("windows-x64".to_string()),
        installation_type: InstallationType::WindowsMsi,
        linux_kernel_version: None,
        linux_glibc_version: None,
        linux_distribution: None,
    }
}

#[test]
fn an_older_client_finds_the_published_release_in_the_index() {
    let index = ReleaseIndex::parse(INDEX, &ManifestPolicy::default()).unwrap();

    let entry = index
        .select_latest_compatible(
            &windows_client(),
            "0.1.0",
            env!("CARGO_PKG_VERSION"),
            &ManifestPolicy::default(),
        )
        .expect("selection must not error")
        .expect("a client on 0.1.0 must be offered the published release");

    assert_eq!(entry.version, "0.1.1");
    assert!(entry.manifest_url.ends_with("release-manifest.json"));
}

#[test]
fn a_current_client_is_offered_nothing() {
    let index = ReleaseIndex::parse(INDEX, &ManifestPolicy::default()).unwrap();

    let entry = index
        .select_latest_compatible(
            &windows_client(),
            "0.1.1",
            env!("CARGO_PKG_VERSION"),
            &ManifestPolicy::default(),
        )
        .expect("selection must not error");

    assert!(
        entry.is_none(),
        "a client already on the published version must not be told to update",
    );
}

#[test]
fn the_selected_artifact_is_the_installer_for_the_running_platform() {
    let manifest = ReleaseManifest::parse(MANIFEST, &ManifestPolicy::default()).unwrap();

    let selection = manifest
        .select_for_platform(&windows_client(), &ManifestPolicy::default())
        .expect("a Windows MSI install must resolve to the MSI artifact");

    assert_eq!(selection.package_format, PackageFormat::Msi);
    assert!(selection.artifact.url.starts_with("https://"));
    assert_eq!(
        selection.artifact.sha256.len(),
        64,
        "an artifact must carry a full SHA-256 for verification",
    );
    assert!(
        selection.artifact.size > 0,
        "an artifact with no recorded size cannot be verified by byte count",
    );
}
